#######    Function to kernel-smooth a cumulative intensity using an
#######        Epanechnikov kernel
#######    Inputs are time t, bandwidth b, and a 'survfit' object generated
#######        by the 'survival' package




#' Kernel-smooth a cumulative intensity using an Epanechnikov kernel
#'
#' @param t time, a single time point.
#' @param b bandwidth.
#' @param surv a [`survival::survfit`] object, generated by the survival package.
#'
#' @return The kernel-smoothed cumulative intensity at time `t`.
#' @export
#'
#' @examples
#' fit <- survival::survfit(survival::Surv(time, status) ~ x, data = survival::aml)
#' sapply(15:45, lambda0_fn, b=10, fit)
lambda0_fn <- function(t, b, surv) {

    times  <- surv$time
    cumhaz <- surv$cumhaz

    increment    <- rep(0,length(times))
    increment[1] <- cumhaz[1]

    for(j in 2:length(times)) {
        increment[j] <- cumhaz[j]-cumhaz[j-1]
    }

    (1/b) *
        sum(
            0.75 * (1 - ( (t - times)/b )^2 ) *
                ( abs(t - times)<b ) * increment
        )
}
