# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pcoriaccel_hello <- function() {
    .Call('_pcoriRPackage_pcoriaccel_hello', PACKAGE = 'pcoriRPackage')
}

pcoriaccel_NW_basic <- function(Xb, Y, xb, y_seq, h) {
    .Call('_pcoriRPackage_pcoriaccel_NW_basic', PACKAGE = 'pcoriRPackage', Xb, Y, xb, y_seq, h)
}

