# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns a string, just as a basic check that the C++ plugin library is working.
#'
#' @return hello string
pcoriaccel_hello <- function() {
    .Call('_pcoriRPackage_pcoriaccel_hello', PACKAGE = 'pcoriRPackage')
}

#' Runs a *basic* implementation of the "NW" function with the "K2_Biweight" kernel, just as a
#' proof-of-concept.
#'
#' @param Xb vector (expected to be about 500 elements)
#' @param Y vector (same size as Xb)
#' @param xb vector
#' @param y_seq vector
#' @param h scalar bandwidth of kernel
#' @return Matrix fyxb
pcoriaccel_NW_basic <- function(Xb, Y, xb, y_seq, h) {
    .Call('_pcoriRPackage_pcoriaccel_NW_basic', PACKAGE = 'pcoriRPackage', Xb, Y, xb, y_seq, h)
}

#' Runs an optimized implementation of the "NW" function.
#'
#' @param Xb vector (expected to be about 500 elements)
#' @param Y vector (same size as Xb)
#' @param xb vector
#' @param y_seq vector
#' @param h scalar bandwidth of kernel
#' @return Matrix fyxb
pcoriaccel_NW <- function(Xb, Y, xb, y_seq, h, kernel = "K2_Biweight") {
    .Call('_pcoriRPackage_pcoriaccel_NW', PACKAGE = 'pcoriRPackage', Xb, Y, xb, y_seq, h, kernel)
}

